language: java
jdk: oraclejdk11
sudo: required
services:
  - mysql
  - docker
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}
after_success:
  - docker login -u "$dockerLogin" -p "$dockerPassword"
  - export IMAGE_NAME=matelord/tourreservations
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:latest
  - docker push $IMAGE_NAME
deploy:
  provider: heroku
  api_key: $herokuToken
  app: torureservations